---
- name : installation
  hosts : websiteToBackup
  roles : 
    - role : backup-db
      exclude_db:
        - Database
        - information_schema
        - sys
        - performance_schema
        - mysql
...